# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    macos:
      xcode: "11.3.0"

    steps:
      - checkout
      - run: pod install # Install CocoaPods dependencies
      - run:
        name: Bundle Install
        command: bundle check || bundle install
        paths:
          - vendor/bundle
      - run: curl -sL firebase.tools | bash
      - run: bundle exec fastlane deploy_firebase

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
build-deploy:
  jobs:
    - build:
        filters:
          branches:
            only: circle-ci
